### ISSUE TITLE
Illegal instruction

### ISSUE THREAD

**Issue by BanTheRewind** [cinder/TinderBox-Win#2]
WRONG TINDERBOX.  This affects projects created for Windows in TinderBox-Mac.

I've been running into this issue for a bit now and I think I've pinpointed it. Whenever I run a release build from a project built with Tinderbox on Windows 7 / Visual Studio 2012, an "Illegal instruction" exception is raised on xmm0. Debug mode works fine. I thought it was a FMOD thing, but now I'm getting in an an empty, new project. It's happening consistently across a few machines with cinder_dev / Win 7 / VC11. It's like SSE is broken or sumpin'. I looked around in the project settings, but nothing stands out.

**Comment by paulhoux** [comment]
I've got the same problem. Cinder master branch, Windows 7 64-bit, Release build in Visual Studio 2012 Express.
Unhandled exception at 0x004183AC in CinderBinPacker.exe: 0xC000001D: Illegal Instruction.

>   CinderBinPacker.exe!std::ctype<char>::_Getcat(const std::locale::facet \* \* _Ppf, const std::locale \* _Ploc) Line 2457   C++
>     CinderBinPacker.exe!std::use_facetstd::ctype<char >(const std::locale & _Loc) Line 560    C++
>     CinderBinPacker.exe!std::basic_ios<char,std::char_traits<char> >::init(std::basic_streambuf<char,std::char_traits<char> > \* _Strbuf, bool _Isstd) Line 178  C++
>     CinderBinPacker.exe!std::basic_ostream<char,std::char_traits<char> >::basic_ostream<char,std::char_traits<char> >(std::basic_streambuf<char,std::char_traits<char> > \* _Strbuf, bool _Isstd) Line 54    C++
>     CinderBinPacker.exe!std::`dynamic initializer for 'cout''() Line 16 C++
>     CinderBinPacker.exe!_cinit(int initFloatingPrecision) Line 290  C
>     CinderBinPacker.exe!__tmainCRTStartup() Line 227    C
>     kernel32.dll!@BaseThreadInitThunk@12() Unknown
>     ntdll.dll!___RtlUserThreadStart@8()    Unknown
>     ntdll.dll!__RtlUserThreadStart@8() Unknown

**Comment by andrewfb** [comment]
Which branch of Cinder?

**Comment by BanTheRewind** [comment]
dev

If I recall correctly, I was getting this on a brand new empty application (ie, non-Cinder) and had the same problem (release only). Leads me to believe this is a general VS / configuration issue.
—

**Comment by paulhoux** [comment]
I am trying to see if the latest update (3) of Visual Studio is installed and, if not, if this will solve the issue. So far, I've tried disabling optimization and intrinsics, but to no avail. 

Cinder's master branch btw.

**Comment by paulhoux** [comment]
Nope, that didn't help. It may be important to know that I am running a Dutch version of Windows.

**Comment by BanTheRewind** [comment]
I have SP 3 and turned off optimization a. Error persists. 
—

**Comment by paulhoux** [comment]
Found it!

Under C/C++  >  Code Generation, set "Enable Enhanced Instruction Set" to  "Not Set"

Then it works.

**Comment by andrewfb** [comment]
Paul are you saying you had to modify those settings for Cinder or for your own project?

**Comment by BanTheRewind** [comment]
Nice. I did the second one, but not the first. The first one should be possible, though. Hmmm...
—

**Comment by paulhoux** [comment]
Sorry 'bout being so vague. I had to change Cinder's project settings, not mine. In my solution, I've included both cinder.vcxproj (vc11) and my own CinderBinPacker.vcxproj (see pull request 362) https://github.com/cinder/Cinder/pull/362  . To make it work, I had to change Cinder's properties. 

Then I had to rebuilt Cinder, of course. All of this was with the Release target. I assume the Debug target doesn't have that setting.

**Comment by andrewfb** [comment]
Oh sure enough - looks like AVX got enabled on accident in this commit: https://github.com/cinder/Cinder/commit/569cfc7014b67dbe8791ce5bb8b8c32d04391e07 I will undo that.

**Comment by paulhoux** [comment]
Shame on you, ChaoticBob :)

**Comment by BanTheRewind** [comment]
Nice one!
—

**Comment by BanTheRewind** [comment]
Ahahaha...
—

**Comment by andrewfb** [comment]
OK - https://github.com/cinder/Cinder/commit/9b2f46bcdf6dfbd699b3b422808c4635125b79ae should address it. I set it to SSE2 instead of AVX, since we may as well.

**Comment by paulhoux** [comment]
And shame on me: it was indeed the "dev" branch and not the "master".
