### ISSUE TITLE
make the 0.9.2 branch to be default branch

### ISSUE THREAD

**Issue by fei4xu** [cinder/TinderBox-Win#5]
I'm using VS2015 so I use cinder + git to get cinder compiled. In that way, I can't find the tinderbox.exe in my \tools\TinderBox-Win folder.

I searched and then I found this repo. Just curious, does it still work with cinder 0.9.2dev?

**Comment by fei4xu** [comment]
oh, please make the 0.9.2 branch to be default branch.

**Comment by andrewfb** [comment]
TinderBox is included from git as a submodule - did you pull submodules in your initial clone of Cinder?

**Comment by fei4xu** [comment]
Yes, I realized it after some search and a re-read of the cinder document.
